export const supabaseUrl = "https://ysxngqggbpgpoihpqycb.supabase.co";
export const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzeG5ncWdnYnBncG9paHBxeWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NTc3MTAsImV4cCI6MjA1ODUzMzcxMH0.gdToYMlmvbEHFIz8Rma7AY6rWbkFqKIg-rZwFZMsWkw";
